#!/usr/bin/env python3
print("Hello there")

name = input("What is your name?\n>> ")

print("Hi " + name)

def askage():
  age = int(input("what is your age? "))
  if age < 60:
    print("How was college? ")
  elif age > 60:
    print("You're old")
  else:
    print("That's interesting.")
  
askage()  
